config/routes.rb
Gallery::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, :skip => [:sessions]
  devise_scope :user do
    match '/users/sign_out(.:format)', {:action=>"destroy", :controller=>"devise/sessions", :via => :delete, :as => :destroy_user_session }
    match '/(.:format)', {:action=>"index", :controller=>"sites", :via => :get, :as => :new_user_session }
  end

  resources :sites
  get '/users/current' => 'users#current', :as => :current_user
  get '/users/login' => 'users#login', :as => :login_user
  get '/users/:provider/:user_key' => 'users#show', :as => :user
  delete '/users/' => 'users#destroy'
  
  get '/page/:page' => 'sites#index'
  root :to => 'sites#index'
end

app/models/site.rb
class Site < ActiveRecord::Base
  validates_presence_of :name, :url, :creator
  validates_length_of :name, :minimum => 3, :maximum => 100
  validates_length_of :url, :minimum => 3, :maximum => 100
  validates_length_of :description, :minimum => 0, :maximum => 1000
  validates_length_of :creator, :minimum => 1, :maximum => 100
  validates_length_of :hash_tag, :minimum => 0, :maximum => 140
  validates_uniqueness_of :url
  validates_url_format_of :url
  validates_url_format_of :repository_url, :allow_nil => true, :allow_blank => true
  
  belongs_to :user
  
  def hash_tags
    '#' + self.hash_tag.split(' ').join(' #')
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_filter :authenticate_user!, :only => [:edit, :update, :destroy]
  # GET /sites
  # GET /sites.json
  def index
    @sites = Site.order('id DESC').page(params[:page]).per(25)
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
    @site = Site.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @site }
    end
  end

  # GET /sites/new
  # GET /sites/new.json
  def new
    @site = Site.new
    @site.url = 'http://'
    @site.creator = current_user.name if user_signed_in?
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @site }
    end
  end

  # GET /sites/1/edit
  def edit
    @site = current_user.sites.find(params[:id])
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(params[:site])
    @site.user_id = current_user.id if user_signed_in?
    respond_to do |format|
      if @site.save
        url = (user_signed_in?)? current_user_path : @site
        format.html { redirect_to url, notice: 'Site was successfully created.' }
        format.json { render json: @site, status: :created, location: @site }
      else
        format.html { render action: "new" }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sites/1
  # PUT /sites/1.json
  def update
    @site = current_user.sites.find(params[:id])

    respond_to do |format|
      if @site.update_attributes(params[:site])
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site = current_user.sites.find(params[:id])
    @site.destroy

    respond_to do |format|
      format.html { redirect_to sites_url, :notice => t('sites.destroy.completed') }
      format.json { head :no_content }
    end
  end
end

app/views/sites/_form.html.erb
<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
 
    <div class="alert alert-block alert-error fade in">
             <a class="close" data-dismiss="alert" href="#">&times;</a>
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :repository_url %><br />
    <%= f.text_field :repository_url %>
  </div>
  <div class="field">
    <%= f.label :creator %><br />
    <%= f.text_field :creator %>
  </div>
  <div class="field">
    <%= f.label :hash_tag %><br />
    #<%= f.text_field :hash_tag %>
  </div>
  <div class="actions">
    <%= f.submit 'save', class:['btn', 'btn-primary'] %>
  </div>
<% end %>

app/views/sites/_index.html.erb
<div id="sites">
  <% if sites.present? %>
  <table class="table table-striped">
    <tr>
      <th>Name</th>
      <th>Creator</th>
      <th>Likes</th>
      <th>Tweets</th>
      <th></th>
    </tr>
  
  <% sites.each do |site| %>
    <%= render 'sites/site', :site => site %>
  <% end %>
  </table>
  <%= paginate sites %>
  <% else %>
  <p class="alert alert-info">
    <%= t('sites._index.nothing_html')%>
  </p>
  <% end %>
</div>

app/views/sites/_site.html.erb
<tr>
  <td class="span3"><%= link_to site.name, site.url, target: '_blank', rel: 'popover', :'data-title' => site.name, :'data-content' => truncate(site.description, :length => 100) %></td>
  <td><%= site.creator %></td>
  <td><div class="fb-like" data-href="<%=site.url%>" data-send="false" data-layout="button_count" data-width="100" data-show-faces="false"></div></td>
  <td>
    <a href="https://twitter.com/share" class="twitter-share-button" data-url="<%=site.url.gsub(/http(s)?:\/\//, '')%>" data-lang="ja" data-text="<%=site.name%>" data-hashtags="<%=site.hash_tag%>">ツイート</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </td>
  <td><%= link_to 'Show', site, class: ['btn'] %></td>
</tr>

app/views/sites/edit.html.erb
<h1>Editing site</h1>

<%= render 'form' %>

app/views/sites/index.html.erb
<%=render 'shared/sns_buttons', :url => 'http://welove.herokuapp.com', :twitter_text => 'we love heroku', :twitter_hash_tag => 'weloveheroku' %>
<div class="hero-unit">
  <h1><%=t(".h1")%></h1>
  <%=t(".description_html")%>
</div>
<%=render 'sites/index', :sites => @sites %>

app/views/sites/new.html.erb
<% unless user_signed_in? %>
  <%= render 'shared/login_button' %>
<% end %>
<h1>New site</h1>
<%= render 'form' %>

app/views/sites/show.html.erb
<% content_for :tw_search_key, @site.hash_tags %>
<%=render 'shared/sns_buttons', :url => @site.url, :twitter_text => @site.url.gsub(/http(s)?:\/\//, ''), :twitter_hash_tag => @site.hash_tag %>
<section id="show">
<div>
  <h3>Name:</h3>
  <p><%= @site.name %></p>
</div>

<div>
  <h3>Url:</h3>
  <p><%= auto_link(@site.url, :link => :urls, :html => {:target => '_blank', :class => :target_blank}) %></p>
</div>

<div>
  <h3>Description:</h3>
  <%= simple_format auto_link(@site.description, :link => :urls, :html => {:target => '_blank'}) %>
</div>

<% if @site.repository_url.present? %>
<div>
  <h3>Repository Url:</h3>
  <p><%= auto_link(@site.repository_url, :link => :urls, :html => {:target => '_blank', :class => :target_blank}) %></p>
</div>
<% end %>

<div>
  <h3>Creator:</h3>
  <p><%= @site.creator %></p>
</div>
<% if @site.hash_tag.present? %>
<div>
  <h3>Has tag:</h3>
  <%=link_to "##{@site.hash_tag.split(' ').join(' #')}", "http://twitter.com/search?q=#{CGI::escape(@site.hash_tags)}" %>
</div>
<% end %>

<% if @site.user.present? %>
<div>
  <h3>Registerd By</h3>
  <%= render 'users/user', :user => @site.user %>
</div>
<% end %>
</section>

<% if user_signed_in? && current_user.id == @site.user_id %>
<section>
<%= link_to edit_site_path(@site), class: ['btn btn-primary'] do %><i class="icon-pencil icon-white"></i>Edit<% end %>
</section>
<section>
<%= link_to site_path(@site), class: ['btn btn-danger'], :method => :delete, :confirm => t('.delete_confirm') do %><i class="icon-trash icon-white"></i>Delete<% end %>
</section>

<% end %>