config/routes.rb
Gallery::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, :skip => [:sessions]
  devise_scope :user do
    match '/users/sign_out(.:format)', {:action=>"destroy", :controller=>"devise/sessions", :via => :delete, :as => :destroy_user_session }
    match '/(.:format)', {:action=>"index", :controller=>"sites", :via => :get, :as => :new_user_session }
  end

  resources :sites
  get '/users/current' => 'users#current', :as => :current_user
  get '/users/login' => 'users#login', :as => :login_user
  get '/users/:provider/:user_key' => 'users#show', :as => :user
  delete '/users/' => 'users#destroy'
  
  get '/page/:page' => 'sites#index'
  root :to => 'sites#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <meta charset="utf-8">
    <title>we love heroku</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <!-- Le fav and touch icons -->
    <link href="/assets/favicon.ico" rel="shortcut icon">
    <link href="/assets/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="/assets/apple-touch-icon-precomposed.png " rel="apple-touch-icon">
    <meta property="og:title" content="we love heroku"/>
    <meta property="og:type" content="website"/>
    <meta property="og:url" content="http://welove.herokuapp.com/"/>
    <meta property="og:site_name" content="we love heroku"/>
    <meta property="og:image" content="http://welove.herokuapp.com/assets/weloveheroku.png" />
    <meta property="fb:admins" content="<%=FacebookConfig.admins%>" />
    <meta property="fb:app_id" content="<%=FacebookConfig.app_id%>" />
    <meta property="og:description" content="this site is gallery which web service hosted on heroku" />
    <script charset="utf-8" src="http://widgets.twimg.com/j/2/widget.js"></script>
    <script src="//platform.twitter.com/widgets.js"></script>
    <%= render 'shared/ga' %>
  </head>
  <body data-spy="scroll" data-target=".subnav" data-offset="50">

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="i-bar"></span>
            <span class="i-bar"></span>
            <span class="i-bar"></span>
          </a>
          <a class="brand" href="/"><%=image_tag 'title.png', :alt => 'we love heroku' %></a>
          <div class="container nav-collapse">
            <ul class="nav">
                <li class="<%=(request.path == root_path ? 'active': '')%>"><%= link_to t(".nav.home"), "/"  %></li>
                <li class="<%=(request.path == new_site_path ? 'active': '')%>"><%= link_to t(".nav.site_add"), new_site_path  %></li>
            </ul>
            <ul class="nav pull-right">
              <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <%= image_tag current_user.image, :size => '20x20', :class => :face %>
                  <%= current_user.name %>
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li class="<%=(request.path == user_path ? 'active': '')%>"><%=link_to t('.nav.user'), current_user_path%></li>
                  <li><%= link_to t('.nav.logout'), destroy_user_session_path, :method => :delete %></li>
                </ul>
              </li>
              <% else %>
                <li><%= link_to t('.nav.login'), login_user_path %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="content">
          <div class="row">
            <div class="span9">
              <% if notice.present? %>
              <div class="alert  alert-success fade in">
                <a class="close" data-dismiss="alert" href="#">&times;</a>
                <p id="notice"><%= notice %></p>
              </div>
              <% end %>
              <%= yield %>
            </div>
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>twitter search result</h3>
                <%= render 'shared/twitter', :tw_search_key => yield(:tw_search_key) %>
            </div>
           </div>
          </div>
        </div>

      <footer id="pagefooter">
        <p>&copy; <%= link_to 'ppworks', 'http://twitter.com/ppworks' %> <%=Time.current.year%></p>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= render 'shared/fb_load_js' %>
  </body>
</html>